# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_books', '0002_auto_20180714_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usersonetomany', to='like_books.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(related_name='usersmanytomany', to='like_books.Book'),
        ),
    ]
