# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_books', '0003_auto_20180714_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='like_books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(related_name='liked_books', to='like_books.Book'),
        ),
    ]
