# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_books', '0004_auto_20180714_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='books',
            new_name='liked_users',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='book',
            new_name='uploader',
        ),
    ]
