# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(verbose_name='Random String to Fill Preexisting Rows'),
        ),
    ]
